package kolbasa.consumer.sweep

import kolbasa.Kolbasa
import kolbasa.consumer.ConsumerSchemaHelpers
import kolbasa.inspector.connection.ConnectionAwareDatabaseInspector
import kolbasa.inspector.connection.ConnectionAwareInspector
import kolbasa.queue.Queue
import kolbasa.schema.Const
import kolbasa.schema.NodeId
import kolbasa.stats.sql.SqlDumpHelper
import kolbasa.stats.sql.StatementKind
import kolbasa.utils.JdbcHelpers.useStatement
import kolbasa.utils.TimeHelper
import java.sql.Connection
import java.time.Duration
import java.util.concurrent.ThreadLocalRandom
import kotlin.math.max

object SweepHelper {

    fun needSweep(): Boolean {
        val sweepConfig = Kolbasa.sweepConfig

        // Sweep is disabled at all, stop all other checks
        if (!sweepConfig.enabled) {
            return false
        }

        // Check
        if (!checkProbability(sweepConfig.probability)) {
            return false
        }

        return true
    }

    /**
     * Run sweep for a particular queue
     *
     * Sweep tries to remove the maximum value from [SweepConfig.maxMessages] or `limit`, whichever is greater.
     *
     * @return how many expired messages were removed
     */
    fun sweep(connection: Connection, queue: Queue<*>, limit: Int): Int {
        return sweep(connection, queue, NodeId.EMPTY_NODE_ID, limit)
    }

    internal fun sweep(connection: Connection, queue: Queue<*>, nodeId: NodeId, limit: Int): Int {
        val sweepConfig = Kolbasa.sweepConfig

        // Calculate how much messages to sweep
        val messagesToSweep = max(limit, sweepConfig.maxMessages)

        return rawSweep(connection, queue, nodeId, messagesToSweep)
    }

    internal fun checkProbability(probability: Double): Boolean = when (probability) {
        0.0 -> false
        1.0 -> true
        else -> (ThreadLocalRandom.current().nextDouble() <= probability)
    }

    /**
     * Just run sweep without any checks and locks
     */
    private fun rawSweep(connection: Connection, queue: Queue<*>, nodeId: NodeId, maxMessages: Int): Int {
        val deadLetterQueue = queue.deadLetterQueue

        val sweepQuery = if (deadLetterQueue != null) {
            // Move dead messages to DLQ instead of deleting
            ConsumerSchemaHelpers.generateMoveExpiredMessagesToDlqQuery(queue, deadLetterQueue, maxMessages)
        } else {
            // Original behavior — plain delete
            ConsumerSchemaHelpers.generateDeleteExpiredMessagesQuery(queue, maxMessages)
        }

        val statementKind = if (deadLetterQueue != null) {
            StatementKind.SWEEP_TO_DLQ
        } else {
            StatementKind.SWEEP
        }

        val (execution, removedMessages) = TimeHelper.measure {
            connection.useStatement { statement ->
                statement.executeUpdate(sweepQuery)
            }
        }

        // SQL Dump
        SqlDumpHelper.dumpQuery(queue, statementKind, sweepQuery, execution, removedMessages)

        // Prometheus
        queue.queueMetrics.sweepMetrics(
            nodeId = nodeId,
            removedMessages = removedMessages,
            executionNanos = execution.durationNanos,
            connection = connection
        )

        // Also run retention cleanup on DLQ itself
        if (deadLetterQueue != null) {
            val dlqOpts = queue.options.dlqOptions
                ?: error("DLQ queue exists but dlqOptions is null, queue: $queue")

            retentionCleanupByDate(connection, deadLetterQueue, dlqOpts.retention)

            if (dlqOpts.maxMessages != null) {
                retentionCleanupByMaxMessages(connection, deadLetterQueue, dlqOpts.maxMessages)
            }
        }

        // Also run retention cleanup on Archive if enabled
        val archiveQueue = queue.archiveQueue
        if (archiveQueue != null) {
            val arcOpts = queue.options.archiveQueueOptions
                ?: error("Archive queue exists but archiveQueueOptions is null, queue: $queue")

            retentionCleanupByDate(connection, archiveQueue, arcOpts.retention)

            if (arcOpts.maxMessages != null) {
                retentionCleanupByMaxMessages(connection, archiveQueue, arcOpts.maxMessages)
            }
        }

        return removedMessages
    }

    private fun retentionCleanupByDate(
        connection: Connection,
        companionQueue: Queue<*>,
        retention: Duration
    ) {
        // Duration-based retention
        //
        // Optimization trick: we filter by scheduled_at instead of created_at here. For companion queues
        // (DLQ/Archive), both columns have the same value — the move queries set
        // scheduled_at = statement_timestamp() at insertion time, which is the same moment
        // created_at is generated by the DEFAULT. The advantage is that scheduled_at has an
        // index (used for normal message selection), while created_at does not, so this query
        // can use an index scan instead of a seq scan.
        val oldEnough = "statement_timestamp() - ${TimeHelper.generatePostgreSQLInterval(retention)}"

        val deleteByAgeQuery = """
                delete from ${companionQueue.dbTableName}
                where ctid in (
                    select ctid
                    from ${companionQueue.dbTableName}
                    where ${Const.SCHEDULED_AT_COLUMN_NAME} < $oldEnough
                    limit ${Kolbasa.sweepConfig.maxMessages}
                    for update skip locked
                )
            """.trimIndent()

        val (execution, removedMsg) = TimeHelper.measure {
            connection.useStatement { it.executeUpdate(deleteByAgeQuery) }
        }

        SqlDumpHelper.dumpQuery(companionQueue, StatementKind.RETENTION_CLEANUP, deleteByAgeQuery, execution, removedMsg)
    }

    private fun retentionCleanupByMaxMessages(
        connection: Connection,
        companionQueue: Queue<*>,
        maxMessages: Long
    ) {
        // Count-based retention (keep approximately maxMessages)
        //
        // We use ConnectionAwareInspector.count() to get an APPROXIMATE count of messages in the companion queue to avoid a
        // full table scan. If it exceeds maxMessages, we delete the oldest messages.
        val approxMessagesCount = inspector.count(connection, companionQueue).total()

        val toDelete = (approxMessagesCount - maxMessages).coerceIn(0, Kolbasa.sweepConfig.maxMessages.toLong())

        if (toDelete > 0) {
            val deleteByCountQuery = """
                    delete from ${companionQueue.dbTableName}
                    where ctid in (
                        select ctid
                        from ${companionQueue.dbTableName}
                        order by ${Const.SCHEDULED_AT_COLUMN_NAME} asc
                        limit $toDelete
                        for update skip locked
                    )
                """.trimIndent()

            val (execution, removedMsg) = TimeHelper.measure {
                connection.useStatement { it.executeUpdate(deleteByCountQuery) }
            }

            SqlDumpHelper.dumpQuery(companionQueue, StatementKind.RETENTION_CLEANUP, deleteByCountQuery, execution, removedMsg)
        }
    }

    private val inspector: ConnectionAwareInspector = ConnectionAwareDatabaseInspector()
}
