package kolbasa.schema

import kolbasa.cluster.Shard
import kolbasa.queue.Queue
import kolbasa.queue.QueueHelpers
import kolbasa.queue.QueueType
import kolbasa.queue.meta.MetaField
import kolbasa.queue.meta.MetaIndexType
import kolbasa.schema.Table.Companion.hasIndex
import kolbasa.utils.Helpers
import kolbasa.utils.TimeHelper

internal object SchemaGenerator {

    internal fun generateTableSchema(queue: Queue<*>, existingTable: Table?, idRange: IdRange): Schema {
        val mutableSchema = MutableSchema()

        // table
        forTable(queue, existingTable, mutableSchema, idRange)

        // table sequence
        forIdentity(existingTable, mutableSchema, idRange)

        // shard column
        forShard(queue, existingTable, mutableSchema)

        // scheduledAt column
        forScheduledAtColumn(queue, existingTable, mutableSchema)

        // attempts
        forRemainingAttemptsColumn(queue, existingTable, mutableSchema)

        // metadata
        queue.metadata.fields.forEach { metaField ->
            forMetaFieldColumn(queue, metaField, existingTable, mutableSchema)
        }

        // SQL put function (q_<name>_put)
        forPutFunction(queue, existingTable, mutableSchema)

        return Schema(mutableSchema.tables, mutableSchema.indexes)
    }

    internal fun generateRenameTableSchema(queue: Queue<*>, existingTable: Table?, newQueueName: String): Schema {
        if (existingTable == null) {
            // Rename only existing tables
            return Schema.EMPTY
        }

        val newDatabaseTableName = QueueHelpers.generateQueueDbName(newQueueName)
        val statements = mutableListOf(
            "alter table if exists ${queue.dbTableName} RENAME TO $newDatabaseTableName"
        )

        // The put function name and body are derived from the queue name/table, so on rename we drop the old
        // function and (if enabled) create one bound to the new table. Only MAIN queues have put functions.
        if (queue.queueType == QueueType.MAIN) {
            if (existingTable.putFunction != null) {
                // SQL put function exists for the old table
                statements += "drop function if exists ${QueueHelpers.generatePutFunctionName(queue.name)}"
            }

            if (queue.options.sqlPutFunction) {
                // Need to recreate put function for the new queue name
                val newFunctionName = QueueHelpers.generatePutFunctionName(newQueueName)
                statements += generatePutFunctionDdl(queue, newFunctionName, newDatabaseTableName).createAndComment
            }
        }

        return Schema(tableStatements = statements, indexStatements = emptyList())
    }

    internal fun generateDropTableSchema(queue: Queue<*>, existingTable: Table?): Schema {
        if (existingTable == null) {
            // Drop only existing tables
            return Schema.EMPTY
        }

        val statements = mutableListOf<String>()

        // Drop the put function (if any) before the table. Bare-name DROP works on PG 10+ and no-ops if absent.
        if (queue.queueType == QueueType.MAIN) {
            if (existingTable.putFunction != null) {
                // SQL put function exists for the old table, drop it
                statements += "drop function if exists ${QueueHelpers.generatePutFunctionName(queue.name)}"
            }
        }

        statements += "drop table if exists ${queue.dbTableName}"
        return Schema(tableStatements = statements, indexStatements = emptyList())
    }

    private fun forTable(queue: Queue<*>, existingTable: Table?, mutableSchema: MutableSchema, idRange: IdRange) {
        val createTableStatement = """
            create table if not exists ${queue.dbTableName}(
                ${Const.ID_COLUMN_NAME} bigint generated by default as identity (minvalue ${idRange.min} maxvalue ${idRange.max} cache ${idRange.cache} cycle) primary key,
                ${Const.USELESS_COUNTER_COLUMN_NAME} int,
                ${Const.OPENTELEMETRY_COLUMN_NAME} varchar(${Const.OPENTELEMETRY_VALUE_LENGTH})[],
                ${Const.SHARD_COLUMN_NAME} int not null default ${Shard.MIN_SHARD},
                ${Const.CREATED_AT_COLUMN_NAME} timestamp not null default statement_timestamp(),
                ${Const.SCHEDULED_AT_COLUMN_NAME} timestamp not null default clock_timestamp(),
                ${Const.PROCESSING_AT_COLUMN_NAME} timestamp,
                ${Const.PRODUCER_COLUMN_NAME} varchar(${Const.PRODUCER_CONSUMER_VALUE_MAX_LENGTH}),
                ${Const.CONSUMER_COLUMN_NAME} varchar(${Const.PRODUCER_CONSUMER_VALUE_MAX_LENGTH}),
                ${Const.REMAINING_ATTEMPTS_COLUMN_NAME} int not null,
                ${Const.DATA_COLUMN_NAME} ${queue.databaseDataType.dbColumnType} not null
            )
            """.trimIndent()

        if (existingTable == null) {
            mutableSchema.tables += createTableStatement
        }
    }

    private fun forIdentity(existingTable: Table?, mutableSchema: MutableSchema, idRange: IdRange) {
        if (existingTable == null) {
            // If table does not exist, we can't adjust identity column because there is no such column
            // CREATE TABLE statement will create identity column with the desired settings automatically
            return
        }

        requireNotNull(existingTable.identity) {
            // This should not happen in normal circumstances, because if the table exists, it should have an identity column
            "Queue table ${existingTable.name} exists but does not have an identity column. This likely means that the table " +
                "was not created by Kolbasa or was modified in a non-compatible way. Please check the existing table schema " +
                "and adjust it manually to match the expected schema, or drop the existing table if it is not needed."
        }

        val needToAlterIdentity = (existingTable.identity.min != idRange.min) ||
            (existingTable.identity.max != idRange.max) ||
            (existingTable.identity.cache != idRange.cache)

        val alterSequenceStatement = """
                alter sequence ${existingTable.identity.name}
                restart with ${idRange.min}
                start with ${idRange.min}
                minvalue ${idRange.min}
                maxvalue ${idRange.max}
                cache ${idRange.cache}
                cycle
            """.trimIndent()

        if (needToAlterIdentity) {
            mutableSchema.tables += alterSequenceStatement
        }
    }

    private fun forShard(queue: Queue<*>, existingTable: Table?, mutableSchema: MutableSchema) {
        val indexName = queue.dbTableName + "_" + Const.SHARD_COLUMN_NAME
        val indexStatement =
            "create index concurrently if not exists $indexName on ${queue.dbTableName}(${Const.SHARD_COLUMN_NAME})"

        val hasIndex = existingTable.hasIndex(indexName)
        if (!hasIndex) {
            mutableSchema.indexes += indexStatement
        }
    }

    private fun forScheduledAtColumn(queue: Queue<*>, existingTable: Table?, mutableSchema: MutableSchema) {
        if (existingTable != null) {
            val currentDefault = existingTable.findColumn(Const.SCHEDULED_AT_COLUMN_NAME)?.defaultExpression
            if (currentDefault != "clock_timestamp()") {
                mutableSchema.tables +=
                    "alter table ${queue.dbTableName} alter ${Const.SCHEDULED_AT_COLUMN_NAME} set default clock_timestamp()"
            }
        }

        // index
        val indexName = queue.dbTableName + "_" + Const.SCHEDULED_AT_COLUMN_NAME
        val indexStatement =
            "create index concurrently if not exists $indexName on ${queue.dbTableName}(${Const.SCHEDULED_AT_COLUMN_NAME})"

        val hasIndex = existingTable.hasIndex(indexName)
        if (!hasIndex) {
            mutableSchema.indexes += indexStatement
        }
    }

    private fun forRemainingAttemptsColumn(queue: Queue<*>, existingTable: Table?, mutableSchema: MutableSchema) {
        val desiredAttempts = queue.options.defaultAttempts
        val currentDefaultClause = existingTable
            ?.findColumn(Const.REMAINING_ATTEMPTS_COLUMN_NAME)
            ?.defaultExpression

        val alterStatement =
            "alter table ${queue.dbTableName} alter ${Const.REMAINING_ATTEMPTS_COLUMN_NAME} set default $desiredAttempts"

        if (desiredAttempts.toString() != currentDefaultClause) {
            mutableSchema.tables += alterStatement
        }
    }

    private fun forMetaFieldColumn(
        queue: Queue<*>,
        metaField: MetaField<*>,
        existingTable: Table?,
        mutableSchema: MutableSchema
    ) {
        val hasColumn = existingTable?.findColumn(metaField.dbColumnName) != null
        val alterStatement =
            "alter table ${queue.dbTableName} add if not exists ${metaField.dbColumnName} ${metaField.dbColumnType}"

        if (!hasColumn) {
            mutableSchema.tables += alterStatement
        }

        // index
        val justIndexName = QueueHelpers.generateMetaColumnIndexName(queue.dbTableName, metaField.name, "j")
        val strictUniqueIndexName = QueueHelpers.generateMetaColumnIndexName(queue.dbTableName, metaField.name, "su")
        val pendingUniqueIndexName = QueueHelpers.generateMetaColumnIndexName(queue.dbTableName, metaField.name, "pu")

        val hasJustIndex = existingTable.hasIndex(justIndexName)
        val hasStrictUniqueIndex = existingTable.hasIndex(strictUniqueIndexName)
        val hasPendingUniqueIndex = existingTable.hasIndex(pendingUniqueIndexName)

        val dropJustIndexStatement = "drop index concurrently if exists $justIndexName"
        val dropStrictUniqueIndexStatement = "drop index concurrently if exists $strictUniqueIndexName"
        val dropPendingUniqueIndexStatement = "drop index concurrently if exists $pendingUniqueIndexName"

        when (metaField.dbIndexType) {
            MetaIndexType.NO_INDEX -> {
                // NO_INDEX means we need to drop all existing indexes if they exist
                if (existingTable != null) {
                    if (hasJustIndex) {
                        mutableSchema.indexes += dropJustIndexStatement
                    }
                    if (hasStrictUniqueIndex) {
                        mutableSchema.indexes += dropStrictUniqueIndexStatement
                    }
                    if (hasPendingUniqueIndex) {
                        mutableSchema.indexes += dropPendingUniqueIndexStatement
                    }
                }
            }

            MetaIndexType.JUST_INDEX -> {
                val createIndexStatement =
                    "create index concurrently if not exists $justIndexName on ${queue.dbTableName}(${metaField.dbColumnName})"

                if (!hasJustIndex) {
                    mutableSchema.indexes += createIndexStatement
                }
                if (hasStrictUniqueIndex) {
                    mutableSchema.indexes += dropStrictUniqueIndexStatement
                }
                if (hasPendingUniqueIndex) {
                    mutableSchema.indexes += dropPendingUniqueIndexStatement
                }
            }

            MetaIndexType.ALL_LIVE_UNIQUE_INDEX -> {
                val createIndexStatement = """
                    create unique index concurrently if not exists $strictUniqueIndexName
                    on ${queue.dbTableName}(${metaField.dbColumnName})
                    where (${Const.REMAINING_ATTEMPTS_COLUMN_NAME} > 0)
                """.trimIndent()

                if (hasJustIndex) {
                    mutableSchema.indexes += dropJustIndexStatement
                }
                if (!hasStrictUniqueIndex) {
                    mutableSchema.indexes += createIndexStatement
                }
                if (hasPendingUniqueIndex) {
                    mutableSchema.indexes += dropPendingUniqueIndexStatement
                }
            }

            MetaIndexType.UNTOUCHED_UNIQUE_INDEX -> {
                val createIndexStatement = """
                    create unique index concurrently if not exists $pendingUniqueIndexName
                    on ${queue.dbTableName}(${metaField.dbColumnName})
                    where (${Const.REMAINING_ATTEMPTS_COLUMN_NAME} > 0) and (${Const.PROCESSING_AT_COLUMN_NAME} is null)
                """.trimIndent()

                if (hasJustIndex) {
                    mutableSchema.indexes += dropJustIndexStatement
                }
                if (hasStrictUniqueIndex) {
                    mutableSchema.indexes += dropStrictUniqueIndexStatement
                }
                if (!hasPendingUniqueIndex) {
                    mutableSchema.indexes += createIndexStatement
                }
            }
        }
    }

    // ----------------------------------------------------------------------------------------------------------
    // SQL put function (q_<name>_put)

    private fun forPutFunction(queue: Queue<*>, existingTable: Table?, mutableSchema: MutableSchema) {
        // Only MAIN queues get a put function; DLQ/Archive companions never do.
        if (queue.queueType != QueueType.MAIN) {
            return
        }

        val functionName = QueueHelpers.generatePutFunctionName(queue.name)
        val existing = existingTable?.putFunction

        if (!queue.options.sqlPutFunction) {
            // Flag off: drop the function if it currently exists (idempotent — nothing emitted otherwise).
            if (existing != null) {
                mutableSchema.tables += "drop function if exists $functionName"
            }
            return
        }

        val ddl = generatePutFunctionDdl(queue, functionName, queue.dbTableName)

        // Already current? The hash lives in the function's COMMENT, so this comparison is normalization-proof.
        if (existing?.hash == ddl.hash) {
            return
        }

        // (Re)create. Bare-name DROP IF EXISTS is a no-op when absent and also clears any same-named orphan
        // (e.g. a table dropped manually without our deleteQueues), so drop-then-create is safe in every case.
        // DROP + CREATE + COMMENT in ONE statement string => executeSchemaStatements runs them in a single
        // implicit transaction (atomic; no window where a trigger could hit a missing function).
        mutableSchema.tables += "drop function if exists $functionName; ${ddl.createAndComment}"
    }


    private fun putFunctionArgs(queue: Queue<*>): List<PutArg> {
        val args = mutableListOf<PutArg>()

        // `data` is required and has no default => it must come first
        // PostgreSQL requires that - required params first, optional next
        args += PutArg(Const.DATA_COLUMN_NAME, queue.databaseDataType.dbColumnType, default = null)

        // Fixed control params, identical for every queue. `delay`/`attempts` defaults are baked from the queue
        // options; because the baked literal is part of the create text, any change to defaultDelay/defaultAttempts
        // changes the hash and triggers a regenerate
        args += PutArg("delay", "interval", TimeHelper.generatePostgreSQLInterval(queue.options.defaultDelay))
        args += PutArg("attempts", "int", queue.options.defaultAttempts.toString())
        args += PutArg(Const.SHARD_COLUMN_NAME, "int", Shard.MIN_SHARD.toString())
        args += PutArg(Const.PRODUCER_COLUMN_NAME, "varchar", "null")
        args += PutArg("ignore_duplicates", "boolean", "false")

        // Per-queue meta fields last, in column order, each defaulting to null
        queue.metadata.fields.forEach { field ->
            args += PutArg(field.dbColumnName, field.dbColumnType, "null")
        }

        return args
    }


    // Deterministic CREATE FUNCTION + COMMENT, with the change-detection hash. The hash covers only the CREATE
    // text (the COMMENT embeds it, so it can't be part of its own input).
    private fun generatePutFunctionDdl(queue: Queue<*>, functionName: String, tableName: String): PutFunctionDdl {
        val argList = putFunctionArgs(queue).joinToString(separator = ", ", transform = PutArg::dbDefinition)

        // Meta param names equal the meta column names, and the `data` param equals the data column, so the
        // VALUES list is mostly just the parameter names.
        val metaColumns = queue.metadata.fields.map { it.dbColumnName }
        val insertColumns = (listOf(
            Const.SCHEDULED_AT_COLUMN_NAME,
            Const.REMAINING_ATTEMPTS_COLUMN_NAME,
            Const.SHARD_COLUMN_NAME,
            Const.PRODUCER_COLUMN_NAME
        ) + metaColumns + Const.DATA_COLUMN_NAME).joinToString(separator = ", ")

        val insertValues = (listOf(
            "statement_timestamp() + delay",
            "attempts",
            "shard",
            "producer"
        ) + metaColumns + Const.DATA_COLUMN_NAME).joinToString(separator = ", ")

        val createStatement = """
            create function $functionName($argList) returns bigint language plpgsql set search_path from current as $DOLLAR_QUOTE
            declare
                result_id bigint;
            begin
                if ignore_duplicates then
                    insert into $tableName($insertColumns) values ($insertValues)
                    on conflict do nothing
                    returning ${Const.ID_COLUMN_NAME} into result_id;
                else
                    insert into $tableName($insertColumns) values ($insertValues)
                    returning ${Const.ID_COLUMN_NAME} into result_id;
                end if;
                return result_id;
            end
            $DOLLAR_QUOTE
        """.trimIndent()

        val hash = Helpers.md5Hash(createStatement)
        val commentStatement =
            "comment on function $functionName is '${Const.PUT_FUNCTION_COMMENT_PREFIX}$hash'"

        return PutFunctionDdl(hash = hash, createAndComment = "$createStatement; $commentStatement")
    }
}

// Argument description for the put-function arg like 'meta_priority int default 15'
private data class PutArg(
    val name: String,
    val type: String,
    val default: String?
) {
    val dbDefinition = if (default != null)
        "$name $type default $default"
    else
        "$name $type"
}

// The generated put-function DDL plus the content hash it encodes. `hash` = md5 of the CREATE text;
// `createAndComment` is "create function ...; comment on function ... is 'kolbasa-put:<hash>'". Computing
// both here keeps the hash next to the exact bytes it hashes
private data class PutFunctionDdl(val hash: String, val createAndComment: String)

// PostgreSQL dollar-quote delimiting the function body. The delimiter is always `$`; `kolbasa` is just the
// tag. Written as a regular (escaped) string because Kotlin raw strings have no `\$` escape.
private const val DOLLAR_QUOTE = "\$kolbasa\$"


// Just a holder class for a few mutable lists
private class MutableSchema {
    val tables = mutableListOf<String>()
    val indexes = mutableListOf<String>()
}

