name: On pull request

on: [ pull_request ]

concurrency: on-pull-request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'corretto'

            - name: Build
              run: ./gradlew test --info
