name: On pull request

on:
    pull_request:
        paths-ignore:
            - README.md

concurrency: on-pull-request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup JDK 17
              uses: actions/setup-java@v5
              with:
                  java-version: '17'
                  distribution: 'corretto'
                  cache: 'gradle'

            - name: Build
              run: ./gradlew devSnapshot printDevSnapshotReleaseNote
              env:
                  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
                  GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
                  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                  GITHUB_HEAD_REF: ${{ github.head_ref }}
