name: On push to main

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md

concurrency: on-push-to-main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'corretto'
                  cache: 'gradle'

            - name: Build
              run: ./gradlew final closeAndReleaseStagingRepository printFinalReleaseNote
              env:
                  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
                  GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
                  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                  GITHUB_HEAD_REF: ${{ github.head_ref }}
                  GRGIT_USER: 'x-access-token'
                  GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
